original_repo: https://github.com/hackcu/phase

volunteers_form: https://goo.gl/forms/UnfRf3SQEqrjNGxW2
mentors_form: https://goo.gl/forms/XL5XA0gFpEWbAQG22
hackers_form: https://my.hackcu.org
sponsor_form: mailto:sponsor@hackcu.org
live_page: https://live.hackcu.org/


sass:
    sass_dir: assets/_sass
    style: compressed